### ISSUE TITLE
Support ChangeRequiresRestart Attribute

### ISSUE THREAD

**Issue by bretcope** [NFig/react-settings-panel#1]
I've [added `ChangeRequiresRestartAttribute` to NFig](https://github.com/NFig/NFig/commit/2bd8980a0919ed192b39111928b8f27c3a25dc16) which doesn't really have any effect on NFig itself, but the UI should provide some sort of indication that changes to the setting won't take effect until the application is restarted when it's present.

There is a boolean `ChangeRequiresRestart` property on [`SettingInfo<TTier, TDataCenter>`](https://github.com/NFig/NFig/blob/2bd8980a0919ed192b39111928b8f27c3a25dc16/NFig/SettingInfo.cs) which indicates whether the attribute was present on the setting.

``` csharp
[Setting(true)]
[ChangeRequiresRestart]
public bool SomeSetting { get; private set; }
```

**Comment by rossipedia** [comment]
:+1:

**Comment by rossipedia** [comment]
Supported in 2.0
