### ISSUE TITLE
Provide indications for when an override is not allowed

### ISSUE THREAD

**Issue by bretcope** [NFig/react-settings-panel#2]
I decided to go in a slightly different direction from what we talked about yesterday. Instead of a `[DisallowOverrideFor()]` attribute, I've simply made "allow overrides" part of the definition of a default value.

The abstract [`DefaultSettingValueAttribute`](https://github.com/NFig/NFig/blob/2bd8980a0919ed192b39111928b8f27c3a25dc16/NFig/DefaultValueAttribute.cs) now has an `AllowOverrides` property which defaults to `true`. When people create their own attributes which inherit from it, they'll want to include a parameter for setting that to false. For example:

``` csharp
[Setting(false)]
[TierDefault(Tier.Prod, true, allowOverrides: false)]
public bool SomeSetting { get; private set; }
```

When the default value for any given tier/data center combination has `AllowOverrides` set to false, that default will always be applied, regardless of whether there is an applicable override. The Any/Any default defined by the `Setting` attribute will always allow overrides (if you don't want to allow overrides in any context, it probably doesn't belong in NFig anyway).

In order to tell what allows overrides and what doesn't, [`SettingValue<TTier, TDataCenter>`](https://github.com/NFig/NFig/blob/2bd8980a0919ed192b39111928b8f27c3a25dc16/NFig/SettingValue.cs) now has an `AllowsOverrides` property (it has no meaning when `IsDefault` is false). When you call `SettingInfo.GetDefaultFor(TTier, TDataCenter)`, the `SettingValue` it returns will indicate whether you can set an override for that combination. There is also a shorthand method `SettingInfo.CanSetOverrideFor(TTier, TDataCenter)` if you don't need the `SettingValue` object.

What I think I would do in the UI is simply show disabled buttons for the data centers which you can't override. Perhaps with hover-text which says that overrides aren't allowed. I imagine disallowing overrides by tier will be much more common than by data center, so typically they'd either all be enabled or disabled, but doing it this way would mean there are no special cases. Anyway, that's my suggestion at least.

I'm ready to release stable updates to NFig (and NFig.Redis soon), but I'd like to coordinate those with UI support, so I'm waiting just a little bit. Also, once all of this is in place for the UI, it would be great to redo the sample application. It's gotten pretty outdated.

**Comment by rossipedia** [comment]
Yup, agree with pretty much everything. I plan on wrapping up the `Enum` stuff tomorrow, and then I'll roll these changes in. I also want to look at/chat about maybe rolling some of the stuff that's in the Web layer into NFig, mainly just the data types and the methods to go from `GetAllSettingInfos` to the types that the UI is expecting. I think having that readily available and simplifying the controller methods would go a long way towards adoptability. The closer we can get to just "drop-in" support, the better.

**Comment by bretcope** [comment]
I'm not really sure what data or format the UI needs. Happy to talk about it.

**Comment by rossipedia** [comment]
I'm mainly thinking of the `SettingJsonValue` that we currently convert the `SettingInfo<>`s to. I'll go whip up a branch in `NFig` to give you an idea what I mean

**Comment by rossipedia** [comment]
Closing, as this is now supported in 2.0
