### ISSUE TITLE
Getting to Run

### ISSUE THREAD

**Issue by KyleGobel** [NFig/react-settings-panel#3]
Hey, Wanted to take a look at this.

I'm not very familiar with the newest js trends, but this is what I did.

```
git clone
npm install webpack -g
cd settings-panel
npm install
webpack
```

I get some weirdo errors that are something like this 

```
ERROR in ./src/components/SettingsPanel.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in E:\Tests\NFig.UI\settings-panel\src\components
 @ ./src/components/SettingsPanel.js 8:22-78

ERROR in ./src/components/SettingsPanel.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in E:\Tests\NFig.UI\settings-panel\src\components
 @ ./src/components/SettingsPanel.js 12:23-70
```

All errors are cannot resolve babel modules.  I'm assuming I missed a step somewhere but being not familiar with any of this makes this hard to track down.  I'll dig in a bit deeper tomorrow, but if you happen to know off the top of your head what I missed and could save me a couple hours that'd be nice :)

**Update**
Found the npm scripts, though npm start will throw out the same errors as above

**Comment by KyleGobel** [comment]
Aha, the missing pieces were

`npm install babel-runtime`
`npm install object-assign`

was this oversight for adding them to package.json, or only needed by some?

Anyway, steps I took to get this actually displaying something in the browser

```
npm install webpack -g
git clone <repo>
cd NFig.UI/settings-panel
npm init
npm install babel-runtime
npm install object-assign
npm start
```

**Comment by rossipedia** [comment]
Currently the `settings-panel.js` file in the `dist` folder should be the pre-built version (it's what gets packaged into the `.nupkg` file). You shouldn't have to build it yourself.

However, it does seem as though those packages were missed, thanks for the tip.

**Comment by rossipedia** [comment]
Also, you can `npm run build` to build the `dist` file, if you'd like.
